[package]
name = "popol"
description = "Minimal non-blocking I/O"
readme = "Readme.md"
keywords = ["io", "poll", "async"]
version = "0.2.0"
authors = ["Alexis Sellier <self@cloudhead.io>"]
edition = "2018"
license = "MIT"

[dependencies]
libc = "0.2.71"
